apiVersion: v1
kind: Service
metadata:
  name: warehousemanager-service
spec:
  selector:
    app: warehousemanager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  
